# Generated by Django 5.2.8 on 2025-12-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonbooking', '0004_remove_customer_address_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
