# Generated by Django 5.2.8 on 2025-12-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonbooking', '0006_rename_customer_appointment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salonbooking',
        ),
    ]
